# Build stage
FROM golang:1.21-alpine AS builder

WORKDIR /app
COPY go.mod go.sum ./
RUN go mod download

COPY . .
RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -o ledger

# Runtime stage 
FROM gcr.io/distroless/base-debian12

WORKDIR /app
COPY --from=builder /app/ledger .

EXPOSE 4000
CMD ["/app/ledger"]